#some tips: http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
site_name: Qi Docs
site_description: Documenation for the Qi service
site_favicon: '/img/qi-docs-favicon.ico'
copyright: Copyright &copy; 2015, OSIsoft, LLC
docs_dir: docs
repo_url: https://github.com/osisoft/Qi-Docs
# theme: sphinx_rtd_theme

pages:
- Introduction: 'index.md'
- Preview: 'preview.md'
- API reference: #'Qi Service API Reference.md'
  - Getting started with Qi REST API: 'Overview.md'
  - QiTypes: 'QiTypes.md'
  - QiStreams: 'QiStreams.md'
  - QiStreamBehavior: 'QiStreamBehaviors.md'
  - QiValues: 'Data.md' # or is it Datb.md?
  - Filter expressions: 'Filter Expressions.md'
  - Advanced topics: 'Advanced Topics.md'
- Samples:  'samples.md'
- Support:  'support.md'
